Repository fuzzylabs/MindGPT, pull requests merged in 2023-07, with the labels that each got.

#24 [MIN-26] Add basic UI app
  app/app.py
  app/disclaimer.txt
  poetry.lock
  pyproject.toml
Labels: enhancement

#18 [MIN-25] Add step to deploy model
  .dockerignore
  .github/workflows/ci.yml
  README.md
  pipelines/deployment_pipeline/config_deployment_pipeline.yaml
  pipelines/deployment_pipeline/deployment_pipeline.py
  poetry.lock
  pyproject.toml
  setup_deploy.sh
  steps/deployment_steps/__init__.py
  steps/deployment_steps/deploy_model_step/deploy_model_step.py
  steps/deployment_steps/deploy_model_step/llm_custom_predict.py
  steps/deployment_steps/deploy_model_step/seldon_llm_custom_deployer_step.py
  steps/deployment_steps/deploy_model_step/zenml_llm_custom_model.py
  steps/deployment_steps/fetch_model_step/fetch_model_step.py
  tests/test_steps/test_deployment_steps/test_fetch_model_step.py
Labels: enhancement

#27 [MIN-45] Update Streamlit app to get the inference endpoint
  .dockerignore
  .gitignore
  README.md
  app/app.py
  setup_deploy.sh
Labels: enhancement

#25 [MIN-37] Setting up dvc in repository
  .dvc/.gitignore
  .dvc/config
  .dvcignore
  README.md
  config/__init__.py
  config/config.py
  data/.gitignore
  data/mind_data_raw.csv.dvc
  data/mind_data_validated.csv.dvc
  data/nhs_data_raw.csv.dvc
  data/nhs_data_validated.csv.dvc
  docs/data-version-control.md
  infrastructure/.gitignore
  infrastructure/.terraform.lock.hcl
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/providers.tf
  infrastructure/resource_group/main.tf
  infrastructure/resource_group/output.tf
  infrastructure/resource_group/variables.tf
  infrastructure/storage_account/main.tf
  infrastructure/storage_account/output.tf
  infrastructure/storage_account/variables.tf
  infrastructure/variables.tf
  pipelines/data_preparation_pipeline/config_data_preparation_pipeline.yaml
  pipelines/data_preparation_pipeline/data_preparation_pipeline.py
  poetry.lock
  pyproject.toml
  steps/data_preparation_steps/load_data_step/load_data_step.py
  steps/data_preparation_steps/validate_data_step/validate_data_step.py
  steps/data_scraping_steps/scrape_mind_data/scrape_mind_data_step.py
  steps/data_scraping_steps/scrape_nhs_data/scrape_nhs_data_step.py
  tests/__init__.py
  tests/test_steps/test_data_preparation_steps/__init__.py
  tests/test_steps/test_data_preparation_steps/conftest.py
  tests/test_steps/test_data_preparation_steps/test_load_data_step.py
  tests/test_steps/test_data_preparation_steps/test_validate_data_step.py
Labels: enhancement

#26 [MIN-48] Create embedding pipeline
  pipelines/data_embedding_pipeline/__init__.py
  pipelines/data_embedding_pipeline/config_data_embedding_pipeline.yaml
  pipelines/data_embedding_pipeline/data_embedding_pipeline.py
  run.py
  steps/data_embedding_steps/__init__.py
  steps/data_embedding_steps/embed_data_step/embed_data_step.py
  steps/data_embedding_steps/fetch_data_step/fetch_data_step.py
  tests/test_steps/test_data_embedding_steps/test_fetch_data_step.py
Labels: enhancement

#31 [MIN-39] Add dvc step to data preparation pipeline
  pipelines/data_preparation_pipeline/config_data_preparation_pipeline.yaml
  pipelines/data_preparation_pipeline/data_preparation_pipeline.py
Labels: enhancement

#36 [MIN-61] fix failing test due to dvc module detecting develop branch
  tests/test_steps/test_data_versioning_steps/test_version_data_step.py
Labels: bug

#32 [MIN-49] Create load data from DVC version step
  pipelines/data_embedding_pipeline/config_data_embedding_pipeline.yaml
  pipelines/data_embedding_pipeline/data_embedding_pipeline.py
  poetry.lock
  run.py
  steps/data_embedding_steps/__init__.py
  steps/data_embedding_steps/fetch_data_step/fetch_data_step.py
Labels: enhancement

#39 [MIN-40] add documentation for dvc to repo
  docs/data-version-control.md
Labels: documentation

#40 [MIN-58] Deploy streamlit app on AKS
  .dockerignore
  README.md
  app/.streamlit/config.toml
  app/Dockerfile
  app/app.py
  app/requirements.txt
  app/run.sh
  infrastructure/llm_k8s/seldondeployment.yaml
  infrastructure/streamlit_k8s/streamlit-deployment.yaml
  infrastructure/streamlit_k8s/streamlit-service.yaml
Labels: enhancement

#43 [MIN-68] Update Readme to include running all pipelines locally
  README.md
  steps/data_embedding_steps/embed_data_step/embed_data_step.py
Labels: documentation

#44 [MIN-65] Update chroma application to use latest version
  README.md
  app/app.py
  infrastructure/chroma_server_k8s/chroma-clickhouse-backups-persistentvolumeclaim.yaml
  infrastructure/chroma_server_k8s/chroma-clickhouse-data-persistentvolumeclaim.yaml
  infrastructure/chroma_server_k8s/chroma-configmap.yaml
  infrastructure/chroma_server_k8s/server-deployment.yaml
  infrastructure/chroma_server_k8s/server-service.yaml
  poetry.lock
  pyproject.toml
  steps/data_embedding_steps/embed_data_step/embed_data_step.py
  tests/test_utils/test_chroma_store.py
  utils/chroma_store.py
Labels: enhancement

#45 [MIN-62] Revisit updating `ci.yml` workflow for installing dependencies
  .github/workflows/ci.yml
  pipelines/data_embedding_pipeline/config_data_embedding_pipeline.yaml
  pipelines/data_embedding_pipeline/data_embedding_pipeline.py
  poetry.lock
  pyproject.toml
  steps/data_preparation_steps/validate_data_step/validate_data_step.py
  steps/data_scraping_steps/scrape_mind_data/scrape_mind_data_step.py
  steps/data_scraping_steps/scrape_nhs_data/scrape_nhs_data_step.py
  steps/generic_steps/load_data_step/load_data_step.py
Labels: bug

#47 [MIN-72] Create function to calculate readability score
  monitoring/__init__.py
  monitoring/metric_service.py
  poetry.lock
  pyproject.toml
  tests/test_monitoring/test_metric_service.py
Labels: enhancement
